"""Cross-language Merkle parity: Python SDK ⇄ TypeScript SDK ⇄ MerkleLib.sol.

`sdk/python/avaira/audit.py` documents that "A leaf produced here can be handed to
`AvairaIntentVault.challengeDeviation`" and references this very file — but the file did
not exist, so the Python implementation was never actually pinned to the vectors the
TypeScript SDK generates and the Foundry suite asserts (`contracts/test/MerkleParity.t.sol`).

The vectors in `contracts/test/fixtures/sdk-vectors.json` are generated by the TypeScript
SDK (`npm run vectors`) and checked byte-for-byte against `MerkleLib` by the Foundry suite.
Asserting the *same* vectors here closes the triangle: if Python ever drifts by one byte,
this test fails.
"""
from __future__ import annotations

import json
import os
import re
import sys

import pytest

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(ROOT, "backend"))
sys.path.insert(0, os.path.join(ROOT, "sdk", "python"))

from avaira.audit import merkle_proof, merkle_root, verify_proof  # noqa: E402
from avaira.audit import AuditTrail  # noqa: E402

VECTORS_PATH = os.path.join(ROOT, "contracts", "test", "fixtures", "sdk-vectors.json")
FIXTURE_PATH = os.path.join(ROOT, "contracts", "test", "fixtures", "SdkVectors.sol")


def _vectors():
    with open(VECTORS_PATH, encoding="utf-8") as fh:
        return json.load(fh)


def _fixture_raw_leaves():
    """Raw leaf hashes as the Solidity fixture hardcodes them, grouped by set index."""
    with open(FIXTURE_PATH, encoding="utf-8") as fh:
        source = fh.read()
    sets: dict[int, list[str]] = {}
    pattern = re.compile(r"out\[(\d+)\]\.rawLeaves\[(\d+)\]\s*=\s*(0x[0-9a-fA-F]{64});")
    for set_index, leaf_index, value in pattern.findall(source):
        sets.setdefault(int(set_index), {})[int(leaf_index)] = value.lower()
    return {index: [leaves[i] for i in sorted(leaves)] for index, leaves in sets.items()}


def test_the_vectors_the_fixture_and_the_sdk_agree_on_are_present():
    data = _vectors()
    names = [s["name"] for s in data["sets"]]
    # Leaf counts the audit trail has to survive: 0/1/2/3/5/8 exercise every promotion rule.
    assert names == ["single", "pair", "odd-three", "odd-five", "even-eight"]
    assert _fixture_raw_leaves(), "SdkVectors.sol must contain the raw leaf hashes"


def test_python_leaf_hashes_match_the_solidity_fixture():
    """`AuditTrail.leafFor` must reproduce the leaves `MerkleLib.hashDeviationLeaf` hashes."""
    data = _vectors()
    raw = _fixture_raw_leaves()
    assert len(raw) == len(data["sets"]), "fixture and JSON must describe the same sets"

    for index, vector_set in enumerate(data["sets"]):
        assert len(vector_set["leaves"]) == len(raw[index]), vector_set["name"]
        for leaf, expected in zip(vector_set["leaves"], raw[index]):
            produced = AuditTrail.leaf_for(
                int(leaf["agentId"]),
                data["intentHash"],
                leaf["action"],
                int(leaf["spendUsd"]),
                int(leaf["nonce"]),
            )
            assert produced.lower() == expected, f"{vector_set['name']}: leaf mismatch"


def test_python_merkle_roots_match_the_typescript_vectors():
    data = _vectors()
    for vector_set in data["sets"]:
        leaves = [
            AuditTrail.leaf_for(
                int(leaf["agentId"]), data["intentHash"], leaf["action"], int(leaf["spendUsd"]), int(leaf["nonce"])
            )
            for leaf in vector_set["leaves"]
        ]
        assert merkle_root(leaves).lower() == vector_set["root"].lower(), vector_set["name"]


def test_python_merkle_proofs_match_the_typescript_vectors():
    data = _vectors()
    for vector_set in data["sets"]:
        leaves = [
            AuditTrail.leaf_for(
                int(leaf["agentId"]), data["intentHash"], leaf["action"], int(leaf["spendUsd"]), int(leaf["nonce"])
            )
            for leaf in vector_set["leaves"]
        ]
        for index, expected_proof in enumerate(vector_set["proofs"]):
            produced = [p.lower() for p in merkle_proof(leaves, index)]
            assert produced == [p.lower() for p in expected_proof], f"{vector_set['name']}[{index}]"


def test_every_generated_proof_verifies_against_the_published_root():
    data = _vectors()
    for vector_set in data["sets"]:
        leaves = [
            AuditTrail.leaf_for(
                int(leaf["agentId"]), data["intentHash"], leaf["action"], int(leaf["spendUsd"]), int(leaf["nonce"])
            )
            for leaf in vector_set["leaves"]
        ]
        root = vector_set["root"]
        for index, leaf in enumerate(leaves):
            assert verify_proof(merkle_proof(leaves, index), root, leaf) is True, vector_set["name"]
            # A proof for entry i must not admit entry j (second-preimage / forgery check).
            for other in range(len(leaves)):
                if other == index:
                    continue
                assert verify_proof(merkle_proof(leaves, index), root, leaves[other]) is False


def test_trail_head_and_chain_verify_round_trip():
    data = _vectors()
    trail = AuditTrail(agent_id=7, intent_hash=data["intentHash"])
    trail.append("email.send", spend_usd=100, nonce=0)
    trail.append("db.write", spend_usd=200, nonce=1)
    trail.append("db.write", spend_usd=300, nonce=2)

    valid, broken_at = trail.verify()
    assert (valid, broken_at) == (True, None)
    assert trail.merkle_root() == merkle_root(trail.leaves())

    # Tampering with a middle entry breaks the chain at that point.
    trail.entries[1].spend_usd = 999
    valid, broken_at = trail.verify()
    assert valid is False and broken_at == 1


@pytest.mark.parametrize("count", [0, 1, 2, 3, 4, 5, 8, 9])
def test_odd_and_even_leaf_counts_are_self_consistent(count):
    leaves = [AuditTrail.leaf_for(1, "0x" + "11" * 32, f"action-{i}", i, i) for i in range(count)]
    root = merkle_root(leaves)
    if count == 0:
        assert root == "0x" + "00" * 32
        return
    for index in range(count):
        assert verify_proof(merkle_proof(leaves, index), root, leaves[index]) is True
