// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";

import {MerkleLib} from "avaira/lib/MerkleLib.sol";
import {RiskEnvelope, RiskEnvelopeLib} from "avaira/lib/AvairaTypes.sol";
import {DeviationLeaf} from "avaira/interfaces/IAvaira.sol";

import {SdkVectors} from "./fixtures/SdkVectors.sol";

/// @title MerkleParity
/// @notice Cross-language test: the TypeScript SDK's audit trail must be *admissible* onchain.
///
/// @dev Avaira's core trust claim is that the agent's local, high-throughput audit trail is
///      anchored onchain by a single root, and that anyone holding a leaf from that trail can
///      prove a deviation in `AvairaIntentVault.challengeDeviation`. If the SDK and the
///      contract disagree by a single byte, that claim is false. So the vectors in
///      `fixtures/SdkVectors.sol` are generated by the SDK (`npm run vectors`) and asserted
///      here against the Solidity library, on every test run.
///
///      A drift between the two implementations — a changed domain string, a switched hash,
///      sorted vs unsorted pairs, a promotion rule — fails this suite immediately.
contract MerkleParityTest is Test {
    /* ------------------------------ leaf encoding ----------------------------- */

    /// @notice The SDK's leaf hashes are reproducible by `MerkleLib.hashDeviationLeaf`.
    function test_LeafEncoding_MatchesSolidity() public {
        SdkVectors.Set[] memory sets = SdkVectors.sets();

        for (uint256 s; s < sets.length; ++s) {
            for (uint256 i; i < sets[s].leaves.length; ++i) {
                SdkVectors.Leaf memory leaf = sets[s].leaves[i];
                bytes32 solidityLeaf = MerkleLib.hashDeviationLeaf(
                    DeviationLeaf({
                        agentId: leaf.agentId,
                        intentHash: leaf.intentHash,
                        action: leaf.action,
                        spendUsd: leaf.spendUsd,
                        nonce: leaf.nonce
                    })
                );

                assertEq(
                    solidityLeaf,
                    sets[s].rawLeaves[i],
                    string.concat("leaf hash mismatch: set=", sets[s].name, " index=", vm.toString(i))
                );
            }
        }
    }

    /* ---------------------------------- roots --------------------------------- */

    /// @notice The SDK's Merkle roots equal `MerkleLib.root` for every vector set.
    function test_MerkleRoot_MatchesSolidity() public {
        SdkVectors.Set[] memory sets = SdkVectors.sets();

        for (uint256 s; s < sets.length; ++s) {
            bytes32 solidityRoot = MerkleLib.root(sets[s].rawLeaves);
            assertEq(solidityRoot, sets[s].root, string.concat("root mismatch: set=", sets[s].name));
        }
    }

    /// @notice Every SDK-generated proof verifies inside the onchain library.
    /// @dev This is the exact call `challengeDeviation` makes, so passing here means a
    ///      challenge built by the SDK will be accepted by the vault.
    function test_Proofs_VerifyOnchain() public {
        SdkVectors.Set[] memory sets = SdkVectors.sets();

        for (uint256 s; s < sets.length; ++s) {
            assertEq(sets[s].proofs.length, sets[s].leaves.length, "proof/leaf count mismatch");
            for (uint256 i; i < sets[s].proofs.length; ++i) {
                bool ok = MerkleLib.verify(sets[s].proofs[i], sets[s].root, sets[s].rawLeaves[i]);
                assertTrue(ok, string.concat("proof failed: set=", sets[s].name, " index=", vm.toString(i)));
            }
        }
    }

    /// @notice A proof from one leaf must not validate a different leaf.
    function test_Proofs_DoNotVerifyForWrongLeaf() public {
        SdkVectors.Set[] memory sets = SdkVectors.sets();

        for (uint256 s; s < sets.length; ++s) {
            if (sets[s].leaves.length < 2) continue;
            // Swap leaves 0 and 1: leaf 0's proof must now fail against leaf 1's hash.
            bool ok = MerkleLib.verify(sets[s].proofs[0], sets[s].root, sets[s].rawLeaves[1]);
            assertFalse(ok, "a proof must not validate a sibling leaf");
        }
    }

    /* --------------------------------- envelopes ------------------------------ */

    /// @notice The SDK's envelope hash equals `RiskEnvelopeLib.hash`.
    /// @dev Envelope mismatch is itself a gate rejection reason (`ENVELOPE_MISMATCH`), so a
    ///      hash drift here would block every honest agent.
    function test_EnvelopeHash_MatchesSolidity() public {
        (uint256 maxSpendUsd, string[] memory allowedActions, uint64 deadline, bytes32 expected) = SdkVectors.envelope();

        RiskEnvelope memory envelope =
            RiskEnvelope({maxSpendUsd: maxSpendUsd, allowedActions: allowedActions, deadline: deadline});

        assertEq(RiskEnvelopeLib.hash(envelope), expected, "envelope hash mismatch");
        assertEq(RiskEnvelopeLib.allowedActionsHash(envelope), keccak256(abi.encode(allowedActions)));
    }

    /// @notice The envelope hash is sensitive to every field.
    function test_EnvelopeHash_SensitiveToEveryField() public {
        (uint256 maxSpendUsd, string[] memory allowedActions, uint64 deadline, bytes32 expected) = SdkVectors.envelope();
        RiskEnvelope memory base =
            RiskEnvelope({maxSpendUsd: maxSpendUsd, allowedActions: allowedActions, deadline: deadline});

        RiskEnvelope memory spendChanged = RiskEnvelope({maxSpendUsd: maxSpendUsd + 1, allowedActions: allowedActions, deadline: deadline});
        RiskEnvelope memory deadlineChanged = RiskEnvelope({maxSpendUsd: maxSpendUsd, allowedActions: allowedActions, deadline: deadline + 1});

        string[] memory otherActions = new string[](2);
        otherActions[0] = "mcp.call";
        otherActions[1] = "web.search";
        RiskEnvelope memory actionsChanged = RiskEnvelope({maxSpendUsd: maxSpendUsd, allowedActions: otherActions, deadline: deadline});

        assertTrue(RiskEnvelopeLib.hash(base) != RiskEnvelopeLib.hash(spendChanged));
        assertTrue(RiskEnvelopeLib.hash(base) != RiskEnvelopeLib.hash(deadlineChanged), "order of actions must matter");
        assertTrue(RiskEnvelopeLib.hash(base) != RiskEnvelopeLib.hash(actionsChanged), "action order must matter");
        assertEq(RiskEnvelopeLib.hash(base), expected);
    }

    /* ----------------------------------- fuzz --------------------------------- */

    /// @notice Any tree built by the same rules round-trips: root over the whole set verifies
    ///         the tree for every leaf, and a mutated leaf breaks every proof.
    function testFuzz_TreeRoundTrip(uint8 count, bytes32 leafSeed) public {
        count = uint8(bound(count, 1, 32));

        bytes32[] memory leaves = new bytes32[](count);
        for (uint256 i; i < count; ++i) {
            leaves[i] = keccak256(abi.encode(leafSeed, i));
        }

        bytes32 root = MerkleLib.root(leaves);
        assertTrue(root != bytes32(0), "root must never be zero for a non-empty tree");
        assertEq(root, MerkleLib.root(leaves), "root must be deterministic");

        if (count == 1) {
            assertTrue(MerkleLib.verify(new bytes32[](0), root, leaves[0]), "single leaf is its own root");
        }

        bytes32 tampered = keccak256(abi.encode(leafSeed, uint256(999)));
        for (uint256 i; i < count; ++i) {
            if (tampered == leaves[i]) continue;
            assertFalse(MerkleLib.verify(new bytes32[](0), root, tampered), "empty proof must not admit a foreign leaf");
        }
    }

    /// @notice Sorted-pair hashing makes proofs order-independent: swapping the two children
    ///         of any node yields the same parent.
    function testFuzz_HashPair_IsOrderIndependent(bytes32 a, bytes32 b) public pure {
        assertEq(MerkleLib.hashPair(a, b), MerkleLib.hashPair(b, a));
    }
}
