"""Audit-trail tests, including three-way parity with the TypeScript SDK and Solidity.

The vectors in `contracts/test/fixtures/sdk-vectors.json` are generated by the TypeScript
SDK (`npm run vectors`), asserted against `MerkleLib.sol` by `contracts/test/MerkleParity.t.sol`,
and asserted against this Python implementation here. One byte layout, three languages: if
any of them drifts, one of those three suites fails.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from avaira import AuditTrail, GateReason, GATE_REASON_TEXT, RiskEnvelope, hash_pair, hash_leaf, merkle_proof, merkle_root, verify_proof

FIXTURE = Path(__file__).resolve().parents[3] / "contracts" / "test" / "fixtures" / "sdk-vectors.json"
INTENT = "0x" + "11" * 32


@pytest.fixture(scope="module")
def vectors() -> dict:
    return json.loads(FIXTURE.read_text())


def test_genesis_entry_chains_from_zero():
    trail = AuditTrail(agent_id=7, intent_hash=INTENT)
    entry = trail.append("web.search", 1_000_000)
    assert entry.prev_hash == "0x" + "00" * 32
    assert trail.head == entry.hash


def test_chain_verifies_and_detects_tampering():
    trail = AuditTrail(agent_id=7, intent_hash=INTENT)
    for i in range(10):
        trail.append("mcp.call", i * 1_000)
    assert trail.verify() == (True, None)

    trail.entries[4].spend_usd = 999_999_999
    valid, broken_at = trail.verify()
    assert valid is False
    assert broken_at == 4


def test_identical_work_is_not_replayable_across_intents():
    other = "0x" + "22" * 32
    a = AuditTrail(agent_id=7, intent_hash=INTENT).append("web.search", 1)
    b = AuditTrail(agent_id=7, intent_hash=other).append("web.search", 1)
    assert a.hash != b.hash


def test_merkle_vectors_match_the_solidity_verified_fixture(vectors):
    for vector in vectors["sets"]:
        leaves = []
        for leaf in vector["leaves"]:
            leaves.append(
                AuditTrail.leaf_for(7, INTENT or vectors["intentHash"], leaf["action"], int(leaf["spendUsd"]), int(leaf["nonce"]))
            )
        # the fixture uses its own intent hash
        leaves = [
            AuditTrail.leaf_for(7, vectors["intentHash"], leaf["action"], int(leaf["spendUsd"]), int(leaf["nonce"]))
            for leaf in vector["leaves"]
        ]
        assert merkle_root(leaves) == vector["root"], f"root drifted for set {vector['name']}"

        for index, proof in enumerate(vector["proofs"]):
            assert merkle_proof(leaves, index) == proof, f"proof drifted for {vector['name']} #{index}"
            assert verify_proof(proof, vector["root"], leaves[index])


@pytest.mark.parametrize("size", [2, 3, 5, 8, 16, 33])
def test_every_leaf_has_a_validating_proof(size: int):
    leaves = [merkle_root([f"0x{i:064x}"]) for i in range(size)]
    root = merkle_root(leaves)
    for index, leaf in enumerate(leaves):
        assert verify_proof(merkle_proof(leaves, index), root, leaf)


def test_empty_tree_and_order_independence():
    assert merkle_root([]) == "0x" + "00" * 32
    a, b = "0x" + "ab" * 32, "0x" + "cd" * 32
    assert hash_pair(a, b) == hash_pair(b, a)
    assert hash_leaf(a) != a


def test_deviation_detection_flags_overspend_and_unknown_actions():
    trail = AuditTrail(agent_id=7, intent_hash=INTENT)
    trail.append("web.search", 100_000)
    trail.append("mcp.call", 2_500_000)
    trail.append("swap.execute", 0)
    trail.append("mcp.call", 2_000_000)

    deviations = trail.deviations(max_spend_usd=2_000_000, allowed_actions=["web.search", "mcp.call"])
    assert [d.action for d in deviations] == ["mcp.call", "swap.execute"]
    assert [d.seq for d in deviations] == [1, 2]


def test_deviation_leaf_is_provable_against_the_anchored_root():
    trail = AuditTrail(agent_id=7, intent_hash=INTENT)
    trail.append("web.search", 1_000)
    trail.append("swap.execute", 900_000)

    index = trail.deviations(max_spend_usd=100_000, allowed_actions=["web.search"])[0].seq
    assert verify_proof(trail.proof_for(index), trail.merkle_root(), trail.leaves()[index])


def test_reason_codes_are_documented():
    for reason in GateReason:
        assert reason in GATE_REASON_TEXT
    assert GATE_REASON_TEXT[GateReason.ALLOWED] == "allowed"
    assert int(GateReason.INTENT_NOT_COMMITTED) == 6


def test_envelope_hash_matches_the_solidity_fixture(vectors):
    """`RiskEnvelopeLib.hash` and `Avaira.hash_envelope` must agree byte-for-byte.

    A mismatch here would be rejected by the gate as `ENVELOPE_MISMATCH`, blocking every
    honest Python agent.
    """
    from avaira.client import Avaira

    client = Avaira(
        rpc_url="http://127.0.0.1:1",  # never dialled: hashing is pure
        chain_id=10143,
        contracts={
            "identityRegistry": "0x0000000000000000000000000000000000000001",
            "reputationRegistry": "0x0000000000000000000000000000000000000002",
            "stakeRegistry": "0x0000000000000000000000000000000000000003",
            "intentVault": "0x0000000000000000000000000000000000000004",
        },
    )
    envelope = RiskEnvelope(max_spend_usd=5_000_000, allowed_actions=["web.search", "mcp.call"], deadline=1_893_456_000)
    assert client.hash_envelope(envelope) == vectors["envelopeHash"]
    assert client.hash_envelope(RiskEnvelope(5_000_001, ["web.search", "mcp.call"], 1_893_456_000)) != vectors["envelopeHash"]
